### ISSUE TITLE
Add public IP allowlisting support to Azure dedicated

### ISSUE THREAD

**Issue by abhinavg6** [wandb/terraform-azurerm-wandb#50]
As a basic network security capability, we would like to support public IP allowlisting capability in Azure dedicated. With that, our customers could provide us with public IP addresses or CIDR ranges of their users or egress gateways which we could add to a deployment allowlist on our end. And then any traffic to the deployment would only be allowed from those public IPs.

This feature should work well even if a deployment has Private Link configured. In such a case, a minimum set of public IPs could be used as fallback in case of issues with Private Link as a feature or as a way to access the UI (while private endpoints could be used from ML/DL training workloads).

This feature is already supported in AWS & GCP dedicated.

**Comment by amanpruthi** [comment]
https://github.com/wandb/core/pull/21681
